version: "3.8"

services:
  mi-app:
    container_name: mi-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - apps
    


networks:
  apps:
    external: true
    

  

 
 