version: "3.8"

services:
  mi-app:
    container_name: mi-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    depends_on:
      - sqlserver 
 
  sqlserver:
    container_name: sqlserver
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 1433:1433
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Admin1234!
    volumes:
      - sqlserver_data:/var/opt/mssql
      
volumes:
  sqlserver_data:
 